version: "3.8"

services:
  fr-bot:
    container_name: fr-bot
    build: .
    restart: always #change if you don't want your container restarting
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
